### PR TITLE
Small style changes to the cart, licensee show, as well as change to …

### PR DESCRIPTION
**Pull request by franchizi**
…remove method redirect in Carts controller

@jrmcgarvey @leila-alderman Please review changes I made to the way the cart looks, licensee show page and remove method redirect.

### CODE REVIEW

**Comment by franchizi** [comment]
I made some other stling changes as well that I've added to this pull request.

**Comment by franchizi** [comment]
@jrmcgarvey @leila-alderman This is the last one for this branch, I promise!

**Comment by leila-alderman** [comment]
Lots of shadows! 

Looks good to me. :+1:

**Comment by franchizi** [comment]
> Lots of shadows!
> 
> Looks good to me. 👍

Lol, yes, very shadowy. It gave the feeling of more depth, and made the page feel more substantial to me.

**Comment by leila-alderman** [comment]
Haha, I have nothing against shadows! I'm sure it looks good. I just found it funny that it was basically an all-shadow PR. Made it easy to approve! :smile:

**Pull request merged**
